export enum EMaintenanceType {
    WATER_CHANGE = 'WATER_CHANGE',
    FILTER_MECHANICAL_CLEANING = 'FILTER_MECHANICAL_CLEANING',
    FILTER_BIOLOGICAL_CLEANING = 'FILTER_BIOLOGICAL_CLEANING',
    PLANT_TRIMMING = 'PLANT_TRIMMING',
    FILTER_MEDIA_REPLACEMENT = 'FILTER_MEDIA_REPLACEMENT',
    OTHER = 'OTHER',
}