export enum ENotificationType {
    WATER_ALERT = 'WATER_ALERT',
    MAINTENANCE_REMINDER = 'MAINTENANCE_REMINDER',
    COMPATIBILITY_WARNING = 'COMPATIBILITY_WARNING',
    COMPATIBILITY_ERROR = 'COMPATIBILITY_ERROR',
}